apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo-app-k8s:1.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: DB_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: REDIS_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: APP_ENV
        - name: TOKEN_LIFETIME
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: TOKEN_LIFETIME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todo-app-secret
              key: SECRET_KEY
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: todo-app-secret
              key: SENTRY_DSN

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000