apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
  namespace: my-namespace
type: Opaque
data:
  SECRET_KEY: NDE1MjI5ZTAzNTNhNzhmNWUyOWY1YWY4MzI5ZWFhNWUxZDIzYTM1Y2JhNThjZTIxNWY3MTIzOGY0Y2Y3NzJhMA==
  SENTRY_DSN: aHR0cHM6Ly9lOWIzMmY1YWM2NjZjYTE5OGFkMzM5MDdmYTE5NjFjZUBvNDUwODI1MDk4NzI5ODgxNi5pbmdlc3QudXMuc2VudHJ5LmlvLzQ1MDgyNTA5ODk5ODU3OTI=
