"""Chnages to user model

Revision ID: aee24eb78a36
Revises: f9bdaaa0dc86
Create Date: 2024-11-04 15:36:18.268208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee24eb78a36'
down_revision: Union[str, None] = 'f9bdaaa0dc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
