name: TODO CICD Build

on:
  pull_request:
    types: [closed]
    branches:
      - production
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Create the SSH directory
          mkdir -p ~/.ssh
          
          # Save the SSH private key and set permissions
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Create the known hosts file to bypass host key verification
          touch ~/.ssh/known_hosts
          
          # Test SSH connection with host key verification disabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "echo 'SSH connection successful!'"

      - name: Execute deployment commands
        run: |
          pwd
          ls -la
          cd /home/ubuntu
          ./deploy.sh
